modLoader="javafml"
loaderVersion="[27,)"

[[mods]]
    modId="${mod_id}"
    displayName="${mod_name}"
    description="${mod_description}"
    version="${mod_version}"
    displayURL="https://minecraft.curseforge.com/projects/${mod_slug}"
    authors="${mod_author}"

[[dependencies.consolehud]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.consolehud]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2,)"
    ordering="NONE"
    side="BOTH"